ALTER TABLE accounts
    ADD COLUMN ledger_initialized BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id UUID NOT NULL,
    account_id BIGINT REFERENCES accounts(id),
    transfer_id BIGINT REFERENCES transfers(id),
    ledger_account VARCHAR(32) NOT NULL,
    entry_type VARCHAR(16) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_ledger_entries_positive_amount CHECK (amount > 0),
    CONSTRAINT ck_ledger_entries_account
        CHECK (
            (ledger_account = 'CUSTOMER' AND account_id IS NOT NULL)
            OR (ledger_account = 'OPENING_EQUITY' AND account_id IS NULL)
        ),
    CONSTRAINT ck_ledger_entries_purpose
        CHECK (
            (purpose = 'TRANSFER' AND transfer_id IS NOT NULL AND ledger_account = 'CUSTOMER')
            OR (purpose = 'OPENING_BALANCE' AND transfer_id IS NULL)
        ),
    CONSTRAINT ck_ledger_entries_type CHECK (entry_type IN ('DEBIT', 'CREDIT'))
);

CREATE UNIQUE INDEX uq_ledger_transfer_entry_type
    ON ledger_entries (transfer_id, entry_type)
    WHERE purpose = 'TRANSFER';

CREATE UNIQUE INDEX uq_ledger_account_opening_entry
    ON ledger_entries (account_id)
    WHERE purpose = 'OPENING_BALANCE' AND ledger_account = 'CUSTOMER';

CREATE INDEX ix_ledger_entries_account_id_id
    ON ledger_entries (account_id, id);
